### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by crawfoal** [GreenStepsChatt/greensteps#206]
The README should give a clear, brief description of what this app does and then act as a launch site to other documentation that the reader is looking for. The audience should be people browsing GitHub, and contributors' prospective employers in addition to potential contributors, so overall a somewhat technical audience but not as technical as for the other docs in this repo.

We already have CONTRIBUTING.md and DEVELOPMENT_SETUP.md and those links need to stay in the README. We might also want to create something like ONBOARDING.md that gives a more technical, detailed introduction to the project, with the audience being new contributors.

Maybe we also want to move some of these docs to the Wiki.

[This article](https://blog.cwrichardkim.com/how-to-get-hundreds-of-stars-on-your-github-project-345b065e20a2) by Richard Kim has some good README tips, and [here](https://github.com/florenceloi/hackbright-project/blob/master/README.md) is just one example of a nice README.

**Comment by Neidley** [comment]
Hello :) May I claim this issue?

**Comment by crawfoal** [comment]
Definitely!

Let me know if you have questions as you look around 🙂

**Comment by Neidley** [comment]
@crawfoal, I've been traveling over the past week but I should finally be able to create a PR for this issue and will link it here in the chat in the next day or so 👍

**Comment by crawfoal** [comment]
Sounds good, thanks!

**Comment by crawfoal** [comment]
Hi @Neidley - just wanted to let you know that I moved this repo to a new organization (GreenStepsChatt). crawfoal/greensteps is now my fork (that's why there are no PRs or issues there anymore).

**Comment by Neidley** [comment]
hey! finally back from vacation and can give this my full attention now :)
thank you for your patience!

**Comment by Neidley** [comment]
@crawfoal, I think I got README.md looking good! :) 
look for a link to PR here shortly!

**Comment by Neidley** [comment]
PR #208 ! @crawfoal Let me know if you have any questions, comments, concerns, or additions you'd like to see :)
